///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDemo_Desktop.UI_Element_Test_Area
{
    public partial class GroupBox_Table
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Shuffle(RepoItemInfo cellInfo, RepoItemInfo buttonInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'cellInfo' at 0;0.", cellInfo);
            cellInfo.FindAdapter<Cell>().Click("0;0");
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo' at 0;0.", buttonInfo);
            buttonInfo.FindAdapter<Button>().Click("0;0");
            
           
        }

        public void MergedUserCodeMethod(RepoItemInfo cellInfo, RepoItemInfo buttonInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'cellInfo' at 0;0.", cellInfo);
            cellInfo.FindAdapter<Cell>().Click("0;0");
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo' at 0;0.", buttonInfo);
            buttonInfo.FindAdapter<Button>().Click("0;0");
        }

    }
}
