///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemo_Desktop.UI_Element_Test_Area
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GroupBox_Table recording.
    /// </summary>
    [TestModule("114f5dd4-c263-4b9b-932a-093cd74bc96e", ModuleType.Recording, 1)]
    public partial class GroupBox_Table : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDemo_Desktop.RxDemo_DesktopRepository repository.
        /// </summary>
        public static global::RxDemo_Desktop.RxDemo_DesktopRepository repo = global::RxDemo_Desktop.RxDemo_DesktopRepository.Instance;

        static GroupBox_Table instance = new GroupBox_Table();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GroupBox_Table()
        {
            CellValue = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GroupBox_Table Instance
        {
            get { return instance; }
        }

#region Variables

        string _CellValue;

        /// <summary>
        /// Gets or sets the value of variable CellValue.
        /// </summary>
        [TestVariable("a6866a6e-7a86-45a7-905c-45e024b4281e")]
        public string CellValue
        {
            get { return _CellValue; }
            set { _CellValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Table.Table_Row0' at 0;0.", repo.RxMainFrame.RxTabUIElements.Table.Table_Row0Info, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabUIElements.Table.Table_Row0.Click("0;0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Table.Btn_Shuffle' at 0;0.", repo.RxMainFrame.RxTabUIElements.Table.Btn_ShuffleInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabUIElements.Table.Btn_Shuffle.Click("0;0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'RxMainFrame.RxTabUIElements.Table.Table_Row0' and assigning its value to variable 'CellValue'.", repo.RxMainFrame.RxTabUIElements.Table.Table_Row0Info, new RecordItemIndex(2));
            CellValue = repo.RxMainFrame.RxTabUIElements.Table.Table_Row0.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
