///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemo_Desktop.UI_Element_Test_Area
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GroupBox_Tree recording.
    /// </summary>
    [TestModule("5c60d8bb-9efa-4f85-bbf9-00813aa0fad3", ModuleType.Recording, 1)]
    public partial class GroupBox_Tree : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDemo_Desktop.RxDemo_DesktopRepository repository.
        /// </summary>
        public static global::RxDemo_Desktop.RxDemo_DesktopRepository repo = global::RxDemo_Desktop.RxDemo_DesktopRepository.Instance;

        static GroupBox_Tree instance = new GroupBox_Tree();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GroupBox_Tree()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GroupBox_Tree Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'RxMainFrame.RxTabUIElements.Tree.RanorexStudioFundamentals' at Center.", repo.RxMainFrame.RxTabUIElements.Tree.RanorexStudioFundamentalsInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabUIElements.Tree.RanorexStudioFundamentals.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Tree.Actions' at Center.", repo.RxMainFrame.RxTabUIElements.Tree.ActionsInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabUIElements.Tree.Actions.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
