///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDemo_Desktop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDemo_DesktopRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("975052f4-37d6-4461-8cec-6471990eb218")]
    public partial class RxDemo_DesktopRepository : RepoGenBaseFolder
    {
        static RxDemo_DesktopRepository instance = new RxDemo_DesktopRepository();
        RxDemo_DesktopRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        RxDemo_DesktopRepositoryFolders.List1000AppFolder _list1000;

        /// <summary>
        /// Gets the singleton class instance representing the RxDemo_DesktopRepository element repository.
        /// </summary>
        [RepositoryFolder("975052f4-37d6-4461-8cec-6471990eb218")]
        public static RxDemo_DesktopRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDemo_DesktopRepository() 
            : base("RxDemo_DesktopRepository", "/", null, 0, false, "975052f4-37d6-4461-8cec-6471990eb218", ".\\RepositoryImages\\RxDemo_DesktopRepository975052f4.rximgres")
        {
            _rxmainframe = new RxDemo_DesktopRepositoryFolders.RxMainFrameAppFolder(this);
            _list1000 = new RxDemo_DesktopRepositoryFolders.List1000AppFolder(this);
        }

#region Variables

        string _Tab = "Introduction";

        /// <summary>
        /// Gets or sets the value of variable Tab.
        /// </summary>
        [TestVariable("43a54ce5-75bb-4d2e-88b3-ac36f004a6a3")]
        public string Tab
        {
            get { return _Tab; }
            set { _Tab = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("975052f4-37d6-4461-8cec-6471990eb218")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("a0bed50a-8da5-4ae6-af6a-b2fb3eb8b2a3")]
        public virtual RxDemo_DesktopRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("ba1cede2-09a0-4094-a19c-b630a872c418")]
        public virtual RxDemo_DesktopRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RxDemo_DesktopRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("a0bed50a-8da5-4ae6-af6a-b2fb3eb8b2a3")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RxDemo_DesktopRepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;
            RxDemo_DesktopRepositoryFolders.RxTabStandardFolder _rxtabstandard;
            RepoItemInfo _menutabInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "a0bed50a-8da5-4ae6-af6a-b2fb3eb8b2a3", "")
            {
                _rxtabintroduction = new RxDemo_DesktopRepositoryFolders.RxTabIntroductionFolder(this);
                _rxtabstandard = new RxDemo_DesktopRepositoryFolders.RxTabStandardFolder(this);
                _menutabInfo = new RepoItemInfo(this, "MenuTab", "?/?/tabpage[@accessiblename=$Tab]", "", 30000, null, "5d3f4ca0-21f9-482d-9989-a20d497cad5c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a0bed50a-8da5-4ae6-af6a-b2fb3eb8b2a3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a0bed50a-8da5-4ae6-af6a-b2fb3eb8b2a3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuTab item.
            /// </summary>
            [RepositoryItem("5d3f4ca0-21f9-482d-9989-a20d497cad5c")]
            public virtual Ranorex.TabPage MenuTab
            {
                get
                {
                    return _menutabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The MenuTab item info.
            /// </summary>
            [RepositoryItemInfo("5d3f4ca0-21f9-482d-9989-a20d497cad5c")]
            public virtual RepoItemInfo MenuTabInfo
            {
                get
                {
                    return _menutabInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("e9e0dc2b-2d50-442c-9168-95219630e7ff")]
            public virtual RxDemo_DesktopRepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }

            /// <summary>
            /// The RxTabStandard folder.
            /// </summary>
            [RepositoryFolder("8586da1c-40cb-45cb-92f8-831817af3bb6")]
            public virtual RxDemo_DesktopRepositoryFolders.RxTabStandardFolder RxTabStandard
            {
                get { return _rxtabstandard; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("e9e0dc2b-2d50-442c-9168-95219630e7ff")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtfield_nameInfo;
            RepoItemInfo _linktxt_resetInfo;
            RepoItemInfo _btn_usernameInfo;
            RepoItemInfo _txt_welcomemessageInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "e9e0dc2b-2d50-442c-9168-95219630e7ff", "")
            {
                _txtfield_nameInfo = new RepoItemInfo(this, "TxtField_Name", "?/?/text[@accessiblename='Enter your name']", "", 30000, null, "57cbf07b-d574-4820-80af-2a56f7cdcdb3");
                _linktxt_resetInfo = new RepoItemInfo(this, "LinkTxt_Reset", "?/?/text[@accessiblename='Reset']", "", 30000, null, "4ccdabc7-428b-440a-a3a5-fc687be54362");
                _btn_usernameInfo = new RepoItemInfo(this, "Btn_UserName", "button[@controlname='btnSubmitUserName']", "", 30000, null, "531caa02-70f1-40d7-92ad-7b1aaa0fdefc");
                _txt_welcomemessageInfo = new RepoItemInfo(this, "Txt_WelcomeMessage", "text[@controlname='lblWelcomeMessage']", "", 30000, null, "5bd45be4-2ddc-4551-90f6-b41efe4c7820");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e9e0dc2b-2d50-442c-9168-95219630e7ff")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e9e0dc2b-2d50-442c-9168-95219630e7ff")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtField_Name item.
            /// </summary>
            [RepositoryItem("57cbf07b-d574-4820-80af-2a56f7cdcdb3")]
            public virtual Ranorex.Text TxtField_Name
            {
                get
                {
                    return _txtfield_nameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtField_Name item info.
            /// </summary>
            [RepositoryItemInfo("57cbf07b-d574-4820-80af-2a56f7cdcdb3")]
            public virtual RepoItemInfo TxtField_NameInfo
            {
                get
                {
                    return _txtfield_nameInfo;
                }
            }

            /// <summary>
            /// The LinkTxt_Reset item.
            /// </summary>
            [RepositoryItem("4ccdabc7-428b-440a-a3a5-fc687be54362")]
            public virtual Ranorex.Text LinkTxt_Reset
            {
                get
                {
                    return _linktxt_resetInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LinkTxt_Reset item info.
            /// </summary>
            [RepositoryItemInfo("4ccdabc7-428b-440a-a3a5-fc687be54362")]
            public virtual RepoItemInfo LinkTxt_ResetInfo
            {
                get
                {
                    return _linktxt_resetInfo;
                }
            }

            /// <summary>
            /// The Btn_UserName item.
            /// </summary>
            [RepositoryItem("531caa02-70f1-40d7-92ad-7b1aaa0fdefc")]
            public virtual Ranorex.Button Btn_UserName
            {
                get
                {
                    return _btn_usernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_UserName item info.
            /// </summary>
            [RepositoryItemInfo("531caa02-70f1-40d7-92ad-7b1aaa0fdefc")]
            public virtual RepoItemInfo Btn_UserNameInfo
            {
                get
                {
                    return _btn_usernameInfo;
                }
            }

            /// <summary>
            /// The Txt_WelcomeMessage item.
            /// </summary>
            [RepositoryItem("5bd45be4-2ddc-4551-90f6-b41efe4c7820")]
            public virtual Ranorex.Text Txt_WelcomeMessage
            {
                get
                {
                    return _txt_welcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Txt_WelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("5bd45be4-2ddc-4551-90f6-b41efe4c7820")]
            public virtual RepoItemInfo Txt_WelcomeMessageInfo
            {
                get
                {
                    return _txt_welcomemessageInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabStandardFolder folder.
        /// </summary>
        [RepositoryFolder("8586da1c-40cb-45cb-92f8-831817af3bb6")]
        public partial class RxTabStandardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openInfo;
            RepoItemInfo _rdbmaleInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _text1001Info;
            RepoItemInfo _updowneditInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _cmbdepartmentInfo;
            RepoItemInfo _lblnumberofpersonsnumberInfo;

            /// <summary>
            /// Creates a new RxTabStandard  folder.
            /// </summary>
            public RxTabStandardFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "8586da1c-40cb-45cb-92f8-831817af3bb6", "")
            {
                _openInfo = new RepoItemInfo(this, "Open", "?/?/button[@accessiblename='Open']", "", 30000, null, "62bdf04c-2db6-4c00-9825-3f32a042f472");
                _rdbmaleInfo = new RepoItemInfo(this, "RdbMale", "?/?/radiobutton[@controlname='rdbMale']", "", 30000, null, "65b3885a-3499-4948-9b4a-5227ac0bb026");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", "", 30000, null, "1f4ae7d3-20c8-471a-b90a-265c62c2559c");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", "", 30000, null, "7c4992d2-1de7-40cf-b455-6afe35f06c96");
                _text1001Info = new RepoItemInfo(this, "Text1001", "?/?/text[@controlid='1001']", "", 30000, null, "4c765692-c798-4790-a676-82dca8e32a2f");
                _updowneditInfo = new RepoItemInfo(this, "UpDownEdit", "?/?/text[@controlname='upDownEdit']", "", 30000, null, "036d5dc0-7501-43c1-99bd-5d5efa5c69c8");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "button[@controlname='btnAddPerson']", "", 30000, null, "c283a430-7a50-4972-804f-4899bd4cdb01");
                _cmbdepartmentInfo = new RepoItemInfo(this, "CmbDepartment", "combobox[@controlname='cmbDepartment']", "", 30000, null, "a010cf16-8fcb-4ead-9a27-40a4be1bda0f");
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", "text[@controlname='lblNumberOfPersonsNumber']", "", 30000, null, "7fca98d8-2ad5-4187-bd29-96695530e8f7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8586da1c-40cb-45cb-92f8-831817af3bb6")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8586da1c-40cb-45cb-92f8-831817af3bb6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("62bdf04c-2db6-4c00-9825-3f32a042f472")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("62bdf04c-2db6-4c00-9825-3f32a042f472")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The RdbMale item.
            /// </summary>
            [RepositoryItem("65b3885a-3499-4948-9b4a-5227ac0bb026")]
            public virtual Ranorex.RadioButton RdbMale
            {
                get
                {
                    return _rdbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbMale item info.
            /// </summary>
            [RepositoryItemInfo("65b3885a-3499-4948-9b4a-5227ac0bb026")]
            public virtual RepoItemInfo RdbMaleInfo
            {
                get
                {
                    return _rdbmaleInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("1f4ae7d3-20c8-471a-b90a-265c62c2559c")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("1f4ae7d3-20c8-471a-b90a-265c62c2559c")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("7c4992d2-1de7-40cf-b455-6afe35f06c96")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("7c4992d2-1de7-40cf-b455-6afe35f06c96")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Text1001 item.
            /// </summary>
            [RepositoryItem("4c765692-c798-4790-a676-82dca8e32a2f")]
            public virtual Ranorex.Text Text1001
            {
                get
                {
                    return _text1001Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1001 item info.
            /// </summary>
            [RepositoryItemInfo("4c765692-c798-4790-a676-82dca8e32a2f")]
            public virtual RepoItemInfo Text1001Info
            {
                get
                {
                    return _text1001Info;
                }
            }

            /// <summary>
            /// The UpDownEdit item.
            /// </summary>
            [RepositoryItem("036d5dc0-7501-43c1-99bd-5d5efa5c69c8")]
            public virtual Ranorex.Text UpDownEdit
            {
                get
                {
                    return _updowneditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UpDownEdit item info.
            /// </summary>
            [RepositoryItemInfo("036d5dc0-7501-43c1-99bd-5d5efa5c69c8")]
            public virtual RepoItemInfo UpDownEditInfo
            {
                get
                {
                    return _updowneditInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("c283a430-7a50-4972-804f-4899bd4cdb01")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("c283a430-7a50-4972-804f-4899bd4cdb01")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The CmbDepartment item.
            /// </summary>
            [RepositoryItem("a010cf16-8fcb-4ead-9a27-40a4be1bda0f")]
            public virtual Ranorex.ComboBox CmbDepartment
            {
                get
                {
                    return _cmbdepartmentInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CmbDepartment item info.
            /// </summary>
            [RepositoryItemInfo("a010cf16-8fcb-4ead-9a27-40a4be1bda0f")]
            public virtual RepoItemInfo CmbDepartmentInfo
            {
                get
                {
                    return _cmbdepartmentInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("7fca98d8-2ad5-4187-bd29-96695530e8f7")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("7fca98d8-2ad5-4187-bd29-96695530e8f7")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("ba1cede2-09a0-4094-a19c-b630a872c418")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _testingInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "ba1cede2-09a0-4094-a19c-b630a872c418", "")
            {
                _testingInfo = new RepoItemInfo(this, "Testing", "listitem[@text='Testing']", "listitem[@text='Testing']", 30000, null, "5a97bbb4-784a-469c-85b1-061660b80012");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ba1cede2-09a0-4094-a19c-b630a872c418")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ba1cede2-09a0-4094-a19c-b630a872c418")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Testing item.
            /// </summary>
            [RepositoryItem("5a97bbb4-784a-469c-85b1-061660b80012")]
            public virtual Ranorex.ListItem Testing
            {
                get
                {
                    return _testingInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Testing item info.
            /// </summary>
            [RepositoryItemInfo("5a97bbb4-784a-469c-85b1-061660b80012")]
            public virtual RepoItemInfo TestingInfo
            {
                get
                {
                    return _testingInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
