///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDemo_Desktop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDemo_DesktopRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("975052f4-37d6-4461-8cec-6471990eb218")]
    public partial class RxDemo_DesktopRepository : RepoGenBaseFolder
    {
        static RxDemo_DesktopRepository instance = new RxDemo_DesktopRepository();
        RxDemo_DesktopRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        RxDemo_DesktopRepositoryFolders.List1000AppFolder _list1000;

        /// <summary>
        /// Gets the singleton class instance representing the RxDemo_DesktopRepository element repository.
        /// </summary>
        [RepositoryFolder("975052f4-37d6-4461-8cec-6471990eb218")]
        public static RxDemo_DesktopRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDemo_DesktopRepository() 
            : base("RxDemo_DesktopRepository", "/", null, 0, false, "975052f4-37d6-4461-8cec-6471990eb218", ".\\RepositoryImages\\RxDemo_DesktopRepository975052f4.rximgres")
        {
            _rxmainframe = new RxDemo_DesktopRepositoryFolders.RxMainFrameAppFolder(this);
            _list1000 = new RxDemo_DesktopRepositoryFolders.List1000AppFolder(this);
        }

#region Variables

        string _Tab = "Introduction";

        /// <summary>
        /// Gets or sets the value of variable Tab.
        /// </summary>
        [TestVariable("43a54ce5-75bb-4d2e-88b3-ac36f004a6a3")]
        public string Tab
        {
            get { return _Tab; }
            set { _Tab = value; }
        }

        string _drpdwn = "Testing";

        /// <summary>
        /// Gets or sets the value of variable drpdwn.
        /// </summary>
        [TestVariable("a35428b2-b5d9-411d-b81b-46fbe2906657")]
        public string drpdwn
        {
            get { return _drpdwn; }
            set { _drpdwn = value; }
        }

        string _Gender = "rdbMale";

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("047539aa-cac6-4d5f-8dd5-fcf16af36a56")]
        public string Gender
        {
            get { return _Gender; }
            set { _Gender = value; }
        }

        string _DataBase = "Nicole Wallace (female, 38) Testing";

        /// <summary>
        /// Gets or sets the value of variable DataBase.
        /// </summary>
        [TestVariable("0a182ed5-9e4b-4524-bca1-ca7aae940f7e")]
        public string DataBase
        {
            get { return _DataBase; }
            set { _DataBase = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("975052f4-37d6-4461-8cec-6471990eb218")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("a0bed50a-8da5-4ae6-af6a-b2fb3eb8b2a3")]
        public virtual RxDemo_DesktopRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("ba1cede2-09a0-4094-a19c-b630a872c418")]
        public virtual RxDemo_DesktopRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RxDemo_DesktopRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("a0bed50a-8da5-4ae6-af6a-b2fb3eb8b2a3")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RxDemo_DesktopRepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;
            RxDemo_DesktopRepositoryFolders.RxTabStandardFolder _rxtabstandard;
            RxDemo_DesktopRepositoryFolders.RxTabImageBasedFolder _rxtabimagebased;
            RxDemo_DesktopRepositoryFolders.RxTabUIElementsFolder _rxtabuielements;
            RxDemo_DesktopRepositoryFolders.RxTabUploadFolder _rxtabupload;
            RepoItemInfo _menutabInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "a0bed50a-8da5-4ae6-af6a-b2fb3eb8b2a3", "")
            {
                _rxtabintroduction = new RxDemo_DesktopRepositoryFolders.RxTabIntroductionFolder(this);
                _rxtabstandard = new RxDemo_DesktopRepositoryFolders.RxTabStandardFolder(this);
                _rxtabimagebased = new RxDemo_DesktopRepositoryFolders.RxTabImageBasedFolder(this);
                _rxtabuielements = new RxDemo_DesktopRepositoryFolders.RxTabUIElementsFolder(this);
                _rxtabupload = new RxDemo_DesktopRepositoryFolders.RxTabUploadFolder(this);
                _menutabInfo = new RepoItemInfo(this, "MenuTab", "?/?/tabpage[@accessiblename=$Tab]", "", 30000, null, "5d3f4ca0-21f9-482d-9989-a20d497cad5c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a0bed50a-8da5-4ae6-af6a-b2fb3eb8b2a3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a0bed50a-8da5-4ae6-af6a-b2fb3eb8b2a3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuTab item.
            /// </summary>
            [RepositoryItem("5d3f4ca0-21f9-482d-9989-a20d497cad5c")]
            public virtual Ranorex.TabPage MenuTab
            {
                get
                {
                    return _menutabInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The MenuTab item info.
            /// </summary>
            [RepositoryItemInfo("5d3f4ca0-21f9-482d-9989-a20d497cad5c")]
            public virtual RepoItemInfo MenuTabInfo
            {
                get
                {
                    return _menutabInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("e9e0dc2b-2d50-442c-9168-95219630e7ff")]
            public virtual RxDemo_DesktopRepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }

            /// <summary>
            /// The RxTabStandard folder.
            /// </summary>
            [RepositoryFolder("8586da1c-40cb-45cb-92f8-831817af3bb6")]
            public virtual RxDemo_DesktopRepositoryFolders.RxTabStandardFolder RxTabStandard
            {
                get { return _rxtabstandard; }
            }

            /// <summary>
            /// The RxTabImageBased folder.
            /// </summary>
            [RepositoryFolder("2f710a8e-00af-494d-9518-735a3cc015a2")]
            public virtual RxDemo_DesktopRepositoryFolders.RxTabImageBasedFolder RxTabImageBased
            {
                get { return _rxtabimagebased; }
            }

            /// <summary>
            /// The RxTabUIElements folder.
            /// </summary>
            [RepositoryFolder("15a10b87-dd1c-4fc9-b4c9-d836d69a0274")]
            public virtual RxDemo_DesktopRepositoryFolders.RxTabUIElementsFolder RxTabUIElements
            {
                get { return _rxtabuielements; }
            }

            /// <summary>
            /// The RxTabUpload folder.
            /// </summary>
            [RepositoryFolder("d72cf329-6f50-4784-8fbf-0ed56862ddf5")]
            public virtual RxDemo_DesktopRepositoryFolders.RxTabUploadFolder RxTabUpload
            {
                get { return _rxtabupload; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("e9e0dc2b-2d50-442c-9168-95219630e7ff")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtfield_nameInfo;
            RepoItemInfo _linktxt_resetInfo;
            RepoItemInfo _btn_usernameInfo;
            RepoItemInfo _txt_welcomemessageInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "e9e0dc2b-2d50-442c-9168-95219630e7ff", "")
            {
                _txtfield_nameInfo = new RepoItemInfo(this, "TxtField_Name", "?/?/text[@accessiblename='Enter your name']", "", 30000, null, "57cbf07b-d574-4820-80af-2a56f7cdcdb3");
                _linktxt_resetInfo = new RepoItemInfo(this, "LinkTxt_Reset", "?/?/text[@accessiblename='Reset']", "", 30000, null, "4ccdabc7-428b-440a-a3a5-fc687be54362");
                _btn_usernameInfo = new RepoItemInfo(this, "Btn_UserName", "button[@controlname='btnSubmitUserName']", "", 30000, null, "531caa02-70f1-40d7-92ad-7b1aaa0fdefc");
                _txt_welcomemessageInfo = new RepoItemInfo(this, "Txt_WelcomeMessage", "text[@controlname='lblWelcomeMessage']", "", 30000, null, "5bd45be4-2ddc-4551-90f6-b41efe4c7820");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e9e0dc2b-2d50-442c-9168-95219630e7ff")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e9e0dc2b-2d50-442c-9168-95219630e7ff")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtField_Name item.
            /// </summary>
            [RepositoryItem("57cbf07b-d574-4820-80af-2a56f7cdcdb3")]
            public virtual Ranorex.Text TxtField_Name
            {
                get
                {
                    return _txtfield_nameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtField_Name item info.
            /// </summary>
            [RepositoryItemInfo("57cbf07b-d574-4820-80af-2a56f7cdcdb3")]
            public virtual RepoItemInfo TxtField_NameInfo
            {
                get
                {
                    return _txtfield_nameInfo;
                }
            }

            /// <summary>
            /// The LinkTxt_Reset item.
            /// </summary>
            [RepositoryItem("4ccdabc7-428b-440a-a3a5-fc687be54362")]
            public virtual Ranorex.Text LinkTxt_Reset
            {
                get
                {
                    return _linktxt_resetInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LinkTxt_Reset item info.
            /// </summary>
            [RepositoryItemInfo("4ccdabc7-428b-440a-a3a5-fc687be54362")]
            public virtual RepoItemInfo LinkTxt_ResetInfo
            {
                get
                {
                    return _linktxt_resetInfo;
                }
            }

            /// <summary>
            /// The Btn_UserName item.
            /// </summary>
            [RepositoryItem("531caa02-70f1-40d7-92ad-7b1aaa0fdefc")]
            public virtual Ranorex.Button Btn_UserName
            {
                get
                {
                    return _btn_usernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_UserName item info.
            /// </summary>
            [RepositoryItemInfo("531caa02-70f1-40d7-92ad-7b1aaa0fdefc")]
            public virtual RepoItemInfo Btn_UserNameInfo
            {
                get
                {
                    return _btn_usernameInfo;
                }
            }

            /// <summary>
            /// The Txt_WelcomeMessage item.
            /// </summary>
            [RepositoryItem("5bd45be4-2ddc-4551-90f6-b41efe4c7820")]
            public virtual Ranorex.Text Txt_WelcomeMessage
            {
                get
                {
                    return _txt_welcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Txt_WelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("5bd45be4-2ddc-4551-90f6-b41efe4c7820")]
            public virtual RepoItemInfo Txt_WelcomeMessageInfo
            {
                get
                {
                    return _txt_welcomemessageInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabStandardFolder folder.
        /// </summary>
        [RepositoryFolder("8586da1c-40cb-45cb-92f8-831817af3bb6")]
        public partial class RxTabStandardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _radiobtn_genderInfo;
            RepoItemInfo _txtfield_firstnameInfo;
            RepoItemInfo _txtfield_lastnameInfo;
            RepoItemInfo _txtfield_ageInfo;
            RepoItemInfo _btn_addentryInfo;
            RepoItemInfo _txt_entriesInfo;
            RepoItemInfo _btn_openInfo;
            RepoItemInfo _txt_dataenterInfo;
            RepoItemInfo _btndeletepersonInfo;

            /// <summary>
            /// Creates a new RxTabStandard  folder.
            /// </summary>
            public RxTabStandardFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "8586da1c-40cb-45cb-92f8-831817af3bb6", "")
            {
                _radiobtn_genderInfo = new RepoItemInfo(this, "RadioBtn_Gender", "?/?/radiobutton[@controltext=$Gender]", "", 30000, null, "65b3885a-3499-4948-9b4a-5227ac0bb026");
                _txtfield_firstnameInfo = new RepoItemInfo(this, "TxtField_FirstName", "?/?/text[@accessiblename='First name']", "", 30000, null, "1f4ae7d3-20c8-471a-b90a-265c62c2559c");
                _txtfield_lastnameInfo = new RepoItemInfo(this, "TxtField_LastName", "?/?/text[@accessiblename='Last name']", "", 30000, null, "7c4992d2-1de7-40cf-b455-6afe35f06c96");
                _txtfield_ageInfo = new RepoItemInfo(this, "TxtField_Age", "?/?/text[@controlname='upDownEdit']", "", 30000, null, "036d5dc0-7501-43c1-99bd-5d5efa5c69c8");
                _btn_addentryInfo = new RepoItemInfo(this, "Btn_AddEntry", "button[@controlname='btnAddPerson']", "", 30000, null, "c283a430-7a50-4972-804f-4899bd4cdb01");
                _txt_entriesInfo = new RepoItemInfo(this, "Txt_Entries", "text[@controlname='lblNumberOfPersonsNumber']", "", 30000, null, "7fca98d8-2ad5-4187-bd29-96695530e8f7");
                _btn_openInfo = new RepoItemInfo(this, "Btn_Open", "?/?/button[@accessiblename='Open']", "", 30000, null, "f9312c46-58f8-4652-b163-2dcf257061cf");
                _txt_dataenterInfo = new RepoItemInfo(this, "Txt_DataEnter", "list[@controlname='lstPersonList']/?/?/listitem[@accessiblename>$DataBase]", "", 30000, null, "3a1b81b6-93f7-4c8f-b1ab-e9c40a164d62");
                _btndeletepersonInfo = new RepoItemInfo(this, "BtnDeletePerson", "button[@controlname='btnDeletePerson']", "", 30000, null, "3f51b6e0-9c3f-43fa-9bb9-4729d4564edf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8586da1c-40cb-45cb-92f8-831817af3bb6")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8586da1c-40cb-45cb-92f8-831817af3bb6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RadioBtn_Gender item.
            /// </summary>
            [RepositoryItem("65b3885a-3499-4948-9b4a-5227ac0bb026")]
            public virtual Ranorex.RadioButton RadioBtn_Gender
            {
                get
                {
                    return _radiobtn_genderInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioBtn_Gender item info.
            /// </summary>
            [RepositoryItemInfo("65b3885a-3499-4948-9b4a-5227ac0bb026")]
            public virtual RepoItemInfo RadioBtn_GenderInfo
            {
                get
                {
                    return _radiobtn_genderInfo;
                }
            }

            /// <summary>
            /// The TxtField_FirstName item.
            /// </summary>
            [RepositoryItem("1f4ae7d3-20c8-471a-b90a-265c62c2559c")]
            public virtual Ranorex.Text TxtField_FirstName
            {
                get
                {
                    return _txtfield_firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtField_FirstName item info.
            /// </summary>
            [RepositoryItemInfo("1f4ae7d3-20c8-471a-b90a-265c62c2559c")]
            public virtual RepoItemInfo TxtField_FirstNameInfo
            {
                get
                {
                    return _txtfield_firstnameInfo;
                }
            }

            /// <summary>
            /// The TxtField_LastName item.
            /// </summary>
            [RepositoryItem("7c4992d2-1de7-40cf-b455-6afe35f06c96")]
            public virtual Ranorex.Text TxtField_LastName
            {
                get
                {
                    return _txtfield_lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtField_LastName item info.
            /// </summary>
            [RepositoryItemInfo("7c4992d2-1de7-40cf-b455-6afe35f06c96")]
            public virtual RepoItemInfo TxtField_LastNameInfo
            {
                get
                {
                    return _txtfield_lastnameInfo;
                }
            }

            /// <summary>
            /// The TxtField_Age item.
            /// </summary>
            [RepositoryItem("036d5dc0-7501-43c1-99bd-5d5efa5c69c8")]
            public virtual Ranorex.Text TxtField_Age
            {
                get
                {
                    return _txtfield_ageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtField_Age item info.
            /// </summary>
            [RepositoryItemInfo("036d5dc0-7501-43c1-99bd-5d5efa5c69c8")]
            public virtual RepoItemInfo TxtField_AgeInfo
            {
                get
                {
                    return _txtfield_ageInfo;
                }
            }

            /// <summary>
            /// The Btn_AddEntry item.
            /// </summary>
            [RepositoryItem("c283a430-7a50-4972-804f-4899bd4cdb01")]
            public virtual Ranorex.Button Btn_AddEntry
            {
                get
                {
                    return _btn_addentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_AddEntry item info.
            /// </summary>
            [RepositoryItemInfo("c283a430-7a50-4972-804f-4899bd4cdb01")]
            public virtual RepoItemInfo Btn_AddEntryInfo
            {
                get
                {
                    return _btn_addentryInfo;
                }
            }

            /// <summary>
            /// The Txt_Entries item.
            /// </summary>
            [RepositoryItem("7fca98d8-2ad5-4187-bd29-96695530e8f7")]
            public virtual Ranorex.Text Txt_Entries
            {
                get
                {
                    return _txt_entriesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Txt_Entries item info.
            /// </summary>
            [RepositoryItemInfo("7fca98d8-2ad5-4187-bd29-96695530e8f7")]
            public virtual RepoItemInfo Txt_EntriesInfo
            {
                get
                {
                    return _txt_entriesInfo;
                }
            }

            /// <summary>
            /// The Btn_Open item.
            /// </summary>
            [RepositoryItem("f9312c46-58f8-4652-b163-2dcf257061cf")]
            public virtual Ranorex.Button Btn_Open
            {
                get
                {
                    return _btn_openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_Open item info.
            /// </summary>
            [RepositoryItemInfo("f9312c46-58f8-4652-b163-2dcf257061cf")]
            public virtual RepoItemInfo Btn_OpenInfo
            {
                get
                {
                    return _btn_openInfo;
                }
            }

            /// <summary>
            /// The Txt_DataEnter item.
            /// </summary>
            [RepositoryItem("3a1b81b6-93f7-4c8f-b1ab-e9c40a164d62")]
            public virtual Ranorex.ListItem Txt_DataEnter
            {
                get
                {
                    return _txt_dataenterInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Txt_DataEnter item info.
            /// </summary>
            [RepositoryItemInfo("3a1b81b6-93f7-4c8f-b1ab-e9c40a164d62")]
            public virtual RepoItemInfo Txt_DataEnterInfo
            {
                get
                {
                    return _txt_dataenterInfo;
                }
            }

            /// <summary>
            /// The BtnDeletePerson item.
            /// </summary>
            [RepositoryItem("3f51b6e0-9c3f-43fa-9bb9-4729d4564edf")]
            public virtual Ranorex.Button BtnDeletePerson
            {
                get
                {
                    return _btndeletepersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDeletePerson item info.
            /// </summary>
            [RepositoryItemInfo("3f51b6e0-9c3f-43fa-9bb9-4729d4564edf")]
            public virtual RepoItemInfo BtnDeletePersonInfo
            {
                get
                {
                    return _btndeletepersonInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabImageBasedFolder folder.
        /// </summary>
        [RepositoryFolder("2f710a8e-00af-494d-9518-735a3cc015a2")]
        public partial class RxTabImageBasedFolder : RepoGenBaseFolder
        {
            RepoItemInfo _chkbox_showimageInfo;
            CalendarInfoClass _calendarInfo;
            TheCatInfoClass _thecatInfo;

            /// <summary>
            /// Creates a new RxTabImageBased  folder.
            /// </summary>
            public RxTabImageBasedFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabImageBased", "?/?/tabpage[@controlname='RxTabImageBased']", parentFolder, 30000, null, false, "2f710a8e-00af-494d-9518-735a3cc015a2", "")
            {
                _chkbox_showimageInfo = new RepoItemInfo(this, "ChkBox_ShowImage", "checkbox[@checked='False']", "", 30000, null, "737e200f-bcf0-4d35-9cc8-f8d9b40cc9fd");
                _calendarInfo = new CalendarInfoClass(this);
                _thecatInfo = new TheCatInfoClass(this);
            }

            /// <summary>
            /// The CalendarInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("75732d99-fb03-4315-8202-c6b472e02764")]
            public class CalendarInfoClass : RepoItemInfo
            {
                /// <summary>
                /// CalendarInfoClass class constructor.
                /// </summary>
                public CalendarInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Calendar", "datetime[@controlname='monthCalendar1']", 30000, null, "75732d99-fb03-4315-8202-c6b472e02764")
                { }

                /// <summary>
                /// Gets the Img_Date20 item image.
                /// </summary>
                /// <returns>The Img_Date20 image.</returns>
                [RepositoryImage("396f9551-16f2-469e-b89f-29b55bb558a2")]
                public CompressedImage GetImg_Date20()
                {
                    return GetImage("396f9551-16f2-469e-b89f-29b55bb558a2");
                }

                /// <summary>
                /// Gets the Img_Date20 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("396f9551-16f2-469e-b89f-29b55bb558a2")]
                public CompressedImage GetImg_Date20(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("396f9551-16f2-469e-b89f-29b55bb558a2", cropRect);
                }

                /// <summary>
                /// Gets the Img_Date21 item image.
                /// </summary>
                /// <returns>The Img_Date21 image.</returns>
                [RepositoryImage("083e5d3d-41b4-4589-9206-332ee4bd8699")]
                public CompressedImage GetImg_Date21()
                {
                    return GetImage("083e5d3d-41b4-4589-9206-332ee4bd8699");
                }

                /// <summary>
                /// Gets the Img_Date21 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("083e5d3d-41b4-4589-9206-332ee4bd8699")]
                public CompressedImage GetImg_Date21(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("083e5d3d-41b4-4589-9206-332ee4bd8699", cropRect);
                }

                /// <summary>
                /// Gets the Img_Date22 item image.
                /// </summary>
                /// <returns>The Img_Date22 image.</returns>
                [RepositoryImage("cfb770bc-4026-4433-bde3-d3699777f3c6")]
                public CompressedImage GetImg_Date22()
                {
                    return GetImage("cfb770bc-4026-4433-bde3-d3699777f3c6");
                }

                /// <summary>
                /// Gets the Img_Date22 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("cfb770bc-4026-4433-bde3-d3699777f3c6")]
                public CompressedImage GetImg_Date22(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("cfb770bc-4026-4433-bde3-d3699777f3c6", cropRect);
                }

                /// <summary>
                /// Gets the Img_RightArrow item image.
                /// </summary>
                /// <returns>The Img_RightArrow image.</returns>
                [RepositoryImage("b0fae4a3-b336-49f0-a535-8aee9c2d678e")]
                public CompressedImage GetImg_RightArrow()
                {
                    return GetImage("b0fae4a3-b336-49f0-a535-8aee9c2d678e");
                }

                /// <summary>
                /// Gets the Img_RightArrow item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("b0fae4a3-b336-49f0-a535-8aee9c2d678e")]
                public CompressedImage GetImg_RightArrow(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("b0fae4a3-b336-49f0-a535-8aee9c2d678e", cropRect);
                }
            }

            /// <summary>
            /// The TheCatInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("a46a15ef-b682-47ca-802b-989b92b070ff")]
            public class TheCatInfoClass : RepoItemInfo
            {
                /// <summary>
                /// TheCatInfoClass class constructor.
                /// </summary>
                public TheCatInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "TheCat", "picture[@controlname='TheCat']", 30000, null, "a46a15ef-b682-47ca-802b-989b92b070ff")
                { }

                /// <summary>
                /// Gets the Img_Cat item image.
                /// </summary>
                /// <returns>The Img_Cat image.</returns>
                [RepositoryImage("6ae023cc-4ea5-4a53-a9f6-5af5e70af926")]
                public CompressedImage GetImg_Cat()
                {
                    return GetImage("6ae023cc-4ea5-4a53-a9f6-5af5e70af926");
                }

                /// <summary>
                /// Gets the Img_Cat item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("6ae023cc-4ea5-4a53-a9f6-5af5e70af926")]
                public CompressedImage GetImg_Cat(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("6ae023cc-4ea5-4a53-a9f6-5af5e70af926", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2f710a8e-00af-494d-9518-735a3cc015a2")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2f710a8e-00af-494d-9518-735a3cc015a2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ChkBox_ShowImage item.
            /// </summary>
            [RepositoryItem("737e200f-bcf0-4d35-9cc8-f8d9b40cc9fd")]
            public virtual Ranorex.CheckBox ChkBox_ShowImage
            {
                get
                {
                    return _chkbox_showimageInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkBox_ShowImage item info.
            /// </summary>
            [RepositoryItemInfo("737e200f-bcf0-4d35-9cc8-f8d9b40cc9fd")]
            public virtual RepoItemInfo ChkBox_ShowImageInfo
            {
                get
                {
                    return _chkbox_showimageInfo;
                }
            }

            /// <summary>
            /// The Calendar item.
            /// </summary>
            [RepositoryItem("75732d99-fb03-4315-8202-c6b472e02764")]
            public virtual Ranorex.DateTime Calendar
            {
                get
                {
                    return _calendarInfo.CreateAdapter<Ranorex.DateTime>(true);
                }
            }

            /// <summary>
            /// The Calendar item info.
            /// </summary>
            [RepositoryItemInfo("75732d99-fb03-4315-8202-c6b472e02764")]
            public virtual CalendarInfoClass CalendarInfo
            {
                get
                {
                    return _calendarInfo;
                }
            }

            /// <summary>
            /// The TheCat item.
            /// </summary>
            [RepositoryItem("a46a15ef-b682-47ca-802b-989b92b070ff")]
            public virtual Ranorex.Picture TheCat
            {
                get
                {
                    return _thecatInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The TheCat item info.
            /// </summary>
            [RepositoryItemInfo("a46a15ef-b682-47ca-802b-989b92b070ff")]
            public virtual TheCatInfoClass TheCatInfo
            {
                get
                {
                    return _thecatInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabUIElementsFolder folder.
        /// </summary>
        [RepositoryFolder("15a10b87-dd1c-4fc9-b4c9-d836d69a0274")]
        public partial class RxTabUIElementsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btn_resetInfo;
            RepoItemInfo _grpbox_greenInfo;
            RepoItemInfo _rdbtn_lightInfo;
            RepoItemInfo _lstbox_optionsInfo;
            RepoItemInfo _btn_downInfo;
            RepoItemInfo _treeviewInfo;
            RepoItemInfo _ranorexautomationhelpersInfo;
            RepoItemInfo _buttonupInfo;
            RepoItemInfo _ranorexstudiofundamentalsInfo;
            RepoItemInfo _actionsInfo;

            /// <summary>
            /// Creates a new RxTabUIElements  folder.
            /// </summary>
            public RxTabUIElementsFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabUIElements", "?/?/tabpage[@controlname='RxTabUIElements']", parentFolder, 30000, null, false, "15a10b87-dd1c-4fc9-b4c9-d836d69a0274", "")
            {
                _btn_resetInfo = new RepoItemInfo(this, "Btn_Reset", "?/?/button[@controlname='btnButton1']", "", 30000, null, "960f1b5a-0ed2-4bb9-86da-2bf3dfc573e0");
                _grpbox_greenInfo = new RepoItemInfo(this, "grpBox_Green", "container[@controlname='grpBox']/?/?/container[@controlname='pnlColourPanel']", "", 30000, null, "7e18981c-2501-4b93-9f82-249c26eec1cb");
                _rdbtn_lightInfo = new RepoItemInfo(this, "rdBtn_Light", "container[@controlname='grpBox']/?/?/radiobutton[@controlname='rdbGreenLight']", "", 30000, null, "daf74291-9495-4be0-84f7-9d57cfb59c8d");
                _lstbox_optionsInfo = new RepoItemInfo(this, "Lstbox_Options", ".//?/listitem[@accessiblename>'Hands-on application topics']", "", 30000, null, "8252159a-0dac-4210-8c49-ff7eb4b582b9");
                _btn_downInfo = new RepoItemInfo(this, "Btn_Down", "?//*//button[@text='Down']", "", 30000, null, "8b5d3ff8-9c4a-447f-b705-4c17d46917ce");
                _treeviewInfo = new RepoItemInfo(this, "TreeView", "?/?/tree[@accessiblename='Tree view']", "", 30000, null, "ce1fcc2d-0dee-48c4-b171-551bce4e43ac");
                _ranorexautomationhelpersInfo = new RepoItemInfo(this, "RanorexAutomationHelpers", "tree[@controlname='treTestTreeView']//treeitem[@accessiblename>'Ranorex Automation Helper']", "", 30000, null, "bf217170-912a-447a-8939-9916f0db7604");
                _buttonupInfo = new RepoItemInfo(this, "ButtonUp", "tree[@controlname='treTestTreeView']/?/?/button[@text='Up']", "", 30000, null, "ba4d659b-0e84-4339-afac-8f774afdb06c");
                _ranorexstudiofundamentalsInfo = new RepoItemInfo(this, "RanorexStudioFundamentals", "tree[@controlname='treTestTreeView']/?/?/treeitem[@accessiblename>'Ranorex Studio fundamenta']", "", 30000, null, "5e744527-7063-49d8-b8a2-3df9ef37afcf");
                _actionsInfo = new RepoItemInfo(this, "Actions", "tree[@controlname='treTestTreeView']//treeitem[@accessiblename='Actions']", "", 30000, null, "3e7fd442-9884-4a81-839e-8224bb05e722");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("15a10b87-dd1c-4fc9-b4c9-d836d69a0274")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("15a10b87-dd1c-4fc9-b4c9-d836d69a0274")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Btn_Reset item.
            /// </summary>
            [RepositoryItem("960f1b5a-0ed2-4bb9-86da-2bf3dfc573e0")]
            public virtual Ranorex.Button Btn_Reset
            {
                get
                {
                    return _btn_resetInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_Reset item info.
            /// </summary>
            [RepositoryItemInfo("960f1b5a-0ed2-4bb9-86da-2bf3dfc573e0")]
            public virtual RepoItemInfo Btn_ResetInfo
            {
                get
                {
                    return _btn_resetInfo;
                }
            }

            /// <summary>
            /// The grpBox_Green item.
            /// </summary>
            [RepositoryItem("7e18981c-2501-4b93-9f82-249c26eec1cb")]
            public virtual Ranorex.Container grpBox_Green
            {
                get
                {
                    return _grpbox_greenInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The grpBox_Green item info.
            /// </summary>
            [RepositoryItemInfo("7e18981c-2501-4b93-9f82-249c26eec1cb")]
            public virtual RepoItemInfo grpBox_GreenInfo
            {
                get
                {
                    return _grpbox_greenInfo;
                }
            }

            /// <summary>
            /// The rdBtn_Light item.
            /// </summary>
            [RepositoryItem("daf74291-9495-4be0-84f7-9d57cfb59c8d")]
            public virtual Ranorex.RadioButton rdBtn_Light
            {
                get
                {
                    return _rdbtn_lightInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The rdBtn_Light item info.
            /// </summary>
            [RepositoryItemInfo("daf74291-9495-4be0-84f7-9d57cfb59c8d")]
            public virtual RepoItemInfo rdBtn_LightInfo
            {
                get
                {
                    return _rdbtn_lightInfo;
                }
            }

            /// <summary>
            /// The Lstbox_Options item.
            /// </summary>
            [RepositoryItem("8252159a-0dac-4210-8c49-ff7eb4b582b9")]
            public virtual Ranorex.ListItem Lstbox_Options
            {
                get
                {
                    return _lstbox_optionsInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Lstbox_Options item info.
            /// </summary>
            [RepositoryItemInfo("8252159a-0dac-4210-8c49-ff7eb4b582b9")]
            public virtual RepoItemInfo Lstbox_OptionsInfo
            {
                get
                {
                    return _lstbox_optionsInfo;
                }
            }

            /// <summary>
            /// The Btn_Down item.
            /// </summary>
            [RepositoryItem("8b5d3ff8-9c4a-447f-b705-4c17d46917ce")]
            public virtual Ranorex.Button Btn_Down
            {
                get
                {
                    return _btn_downInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_Down item info.
            /// </summary>
            [RepositoryItemInfo("8b5d3ff8-9c4a-447f-b705-4c17d46917ce")]
            public virtual RepoItemInfo Btn_DownInfo
            {
                get
                {
                    return _btn_downInfo;
                }
            }

            /// <summary>
            /// The TreeView item.
            /// </summary>
            [RepositoryItem("ce1fcc2d-0dee-48c4-b171-551bce4e43ac")]
            public virtual Ranorex.Tree TreeView
            {
                get
                {
                    return _treeviewInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The TreeView item info.
            /// </summary>
            [RepositoryItemInfo("ce1fcc2d-0dee-48c4-b171-551bce4e43ac")]
            public virtual RepoItemInfo TreeViewInfo
            {
                get
                {
                    return _treeviewInfo;
                }
            }

            /// <summary>
            /// The RanorexAutomationHelpers item.
            /// </summary>
            [RepositoryItem("bf217170-912a-447a-8939-9916f0db7604")]
            public virtual Ranorex.TreeItem RanorexAutomationHelpers
            {
                get
                {
                    return _ranorexautomationhelpersInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The RanorexAutomationHelpers item info.
            /// </summary>
            [RepositoryItemInfo("bf217170-912a-447a-8939-9916f0db7604")]
            public virtual RepoItemInfo RanorexAutomationHelpersInfo
            {
                get
                {
                    return _ranorexautomationhelpersInfo;
                }
            }

            /// <summary>
            /// The ButtonUp item.
            /// </summary>
            [RepositoryItem("ba4d659b-0e84-4339-afac-8f774afdb06c")]
            public virtual Ranorex.Button ButtonUp
            {
                get
                {
                    return _buttonupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonUp item info.
            /// </summary>
            [RepositoryItemInfo("ba4d659b-0e84-4339-afac-8f774afdb06c")]
            public virtual RepoItemInfo ButtonUpInfo
            {
                get
                {
                    return _buttonupInfo;
                }
            }

            /// <summary>
            /// The RanorexStudioFundamentals item.
            /// </summary>
            [RepositoryItem("5e744527-7063-49d8-b8a2-3df9ef37afcf")]
            public virtual Ranorex.TreeItem RanorexStudioFundamentals
            {
                get
                {
                    return _ranorexstudiofundamentalsInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The RanorexStudioFundamentals item info.
            /// </summary>
            [RepositoryItemInfo("5e744527-7063-49d8-b8a2-3df9ef37afcf")]
            public virtual RepoItemInfo RanorexStudioFundamentalsInfo
            {
                get
                {
                    return _ranorexstudiofundamentalsInfo;
                }
            }

            /// <summary>
            /// The Actions item.
            /// </summary>
            [RepositoryItem("3e7fd442-9884-4a81-839e-8224bb05e722")]
            public virtual Ranorex.TreeItem Actions
            {
                get
                {
                    return _actionsInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Actions item info.
            /// </summary>
            [RepositoryItemInfo("3e7fd442-9884-4a81-839e-8224bb05e722")]
            public virtual RepoItemInfo ActionsInfo
            {
                get
                {
                    return _actionsInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabUploadFolder folder.
        /// </summary>
        [RepositoryFolder("d72cf329-6f50-4784-8fbf-0ed56862ddf5")]
        public partial class RxTabUploadFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btn_resetInfo;
            RepoItemInfo _btn_startInfo;
            RepoItemInfo _txt_finishedInfo;

            /// <summary>
            /// Creates a new RxTabUpload  folder.
            /// </summary>
            public RxTabUploadFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabUpload", "?/?/tabpage[@controlname='RxTabUpload']", parentFolder, 30000, null, false, "d72cf329-6f50-4784-8fbf-0ed56862ddf5", "")
            {
                _btn_resetInfo = new RepoItemInfo(this, "Btn_Reset", "?/?/element[@accessiblename='Reset upload']", "", 30000, null, "ef0e4291-e1ae-4433-ac58-af4448cbe237");
                _btn_startInfo = new RepoItemInfo(this, "Btn_Start", "button[@controlname='btnStartUpload']", "", 30000, null, "739af7a0-64f5-4f41-824f-7966d2217f2b");
                _txt_finishedInfo = new RepoItemInfo(this, "Txt_Finished", "text[@text='Upload finished']", "", 30000, null, "829184f6-b2a8-4bcc-8c94-187fee8f2806");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d72cf329-6f50-4784-8fbf-0ed56862ddf5")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d72cf329-6f50-4784-8fbf-0ed56862ddf5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Btn_Reset item.
            /// </summary>
            [RepositoryItem("ef0e4291-e1ae-4433-ac58-af4448cbe237")]
            public virtual Ranorex.Unknown Btn_Reset
            {
                get
                {
                    return _btn_resetInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Btn_Reset item info.
            /// </summary>
            [RepositoryItemInfo("ef0e4291-e1ae-4433-ac58-af4448cbe237")]
            public virtual RepoItemInfo Btn_ResetInfo
            {
                get
                {
                    return _btn_resetInfo;
                }
            }

            /// <summary>
            /// The Btn_Start item.
            /// </summary>
            [RepositoryItem("739af7a0-64f5-4f41-824f-7966d2217f2b")]
            public virtual Ranorex.Button Btn_Start
            {
                get
                {
                    return _btn_startInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Btn_Start item info.
            /// </summary>
            [RepositoryItemInfo("739af7a0-64f5-4f41-824f-7966d2217f2b")]
            public virtual RepoItemInfo Btn_StartInfo
            {
                get
                {
                    return _btn_startInfo;
                }
            }

            /// <summary>
            /// The Txt_Finished item.
            /// </summary>
            [RepositoryItem("829184f6-b2a8-4bcc-8c94-187fee8f2806")]
            public virtual Ranorex.Text Txt_Finished
            {
                get
                {
                    return _txt_finishedInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Txt_Finished item info.
            /// </summary>
            [RepositoryItemInfo("829184f6-b2a8-4bcc-8c94-187fee8f2806")]
            public virtual RepoItemInfo Txt_FinishedInfo
            {
                get
                {
                    return _txt_finishedInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("ba1cede2-09a0-4094-a19c-b630a872c418")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _drpdwn_departmentInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "ba1cede2-09a0-4094-a19c-b630a872c418", "")
            {
                _drpdwn_departmentInfo = new RepoItemInfo(this, "drpDwn_Department", "listitem[@text=$drpdwn]", "", 30000, null, "5a97bbb4-784a-469c-85b1-061660b80012");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ba1cede2-09a0-4094-a19c-b630a872c418")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ba1cede2-09a0-4094-a19c-b630a872c418")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The drpDwn_Department item.
            /// </summary>
            [RepositoryItem("5a97bbb4-784a-469c-85b1-061660b80012")]
            public virtual Ranorex.ListItem drpDwn_Department
            {
                get
                {
                    return _drpdwn_departmentInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The drpDwn_Department item info.
            /// </summary>
            [RepositoryItemInfo("5a97bbb4-784a-469c-85b1-061660b80012")]
            public virtual RepoItemInfo drpDwn_DepartmentInfo
            {
                get
                {
                    return _drpdwn_departmentInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
