///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemo_Desktop.Introduction
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Introduction recording.
    /// </summary>
    [TestModule("7af639f8-8b75-40c8-967b-2e8a97290e9c", ModuleType.Recording, 1)]
    public partial class Introduction : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDemo_Desktop.RxDemo_DesktopRepository repository.
        /// </summary>
        public static global::RxDemo_Desktop.RxDemo_DesktopRepository repo = global::RxDemo_Desktop.RxDemo_DesktopRepository.Instance;

        static Introduction instance = new Introduction();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Introduction()
        {
            Name = "Jagadeesh";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Introduction Instance
        {
            get { return instance; }
        }

#region Variables

        string _Name;

        /// <summary>
        /// Gets or sets the value of variable Name.
        /// </summary>
        [TestVariable("d1b932cc-272d-4ab4-a104-1a134e49b111")]
        public string Name
        {
            get { return _Name; }
            set { _Name = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Tab.
        /// </summary>
        [TestVariable("43a54ce5-75bb-4d2e-88b3-ac36f004a6a3")]
        public string Tab
        {
            get { return repo.Tab; }
            set { repo.Tab = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.MenuTab' at 48;11.", repo.RxMainFrame.MenuTabInfo, new RecordItemIndex(0));
            repo.RxMainFrame.MenuTab.Click("48;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabIntroduction.TxtField_Name' at 49;10.", repo.RxMainFrame.RxTabIntroduction.TxtField_NameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabIntroduction.TxtField_Name.Click("49;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Name' with focus on 'RxMainFrame.RxTabIntroduction.TxtField_Name'.", repo.RxMainFrame.RxTabIntroduction.TxtField_NameInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabIntroduction.TxtField_Name.PressKeys(Name);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabIntroduction.Btn_UserName' at 22;15.", repo.RxMainFrame.RxTabIntroduction.Btn_UserNameInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabIntroduction.Btn_UserName.Click("22;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Welcome, Jagadeesh!') on item 'RxMainFrame.RxTabIntroduction.Txt_WelcomeMessage'.", repo.RxMainFrame.RxTabIntroduction.Txt_WelcomeMessageInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabIntroduction.Txt_WelcomeMessageInfo, "Text", "Welcome, Jagadeesh!");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabIntroduction.LinkTxt_Reset' at Center.", repo.RxMainFrame.RxTabIntroduction.LinkTxt_ResetInfo, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabIntroduction.LinkTxt_Reset.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
