///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemo_Desktop.DynamicIDs
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DynamicIDs recording.
    /// </summary>
    [TestModule("082f750f-7a3b-49bf-93dc-e787e46107fb", ModuleType.Recording, 1)]
    public partial class DynamicIDs : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDemo_Desktop.RxDemo_DesktopRepository repository.
        /// </summary>
        public static global::RxDemo_Desktop.RxDemo_DesktopRepository repo = global::RxDemo_Desktop.RxDemo_DesktopRepository.Instance;

        static DynamicIDs instance = new DynamicIDs();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DynamicIDs()
        {
            firstID = "";
            secID = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DynamicIDs Instance
        {
            get { return instance; }
        }

#region Variables

        string _firstID;

        /// <summary>
        /// Gets or sets the value of variable firstID.
        /// </summary>
        [TestVariable("636d8408-6b64-41b6-be19-aa84e56997cb")]
        public string firstID
        {
            get { return _firstID; }
            set { _firstID = value; }
        }

        string _secID;

        /// <summary>
        /// Gets or sets the value of variable secID.
        /// </summary>
        [TestVariable("0ff0a4fd-f827-4dd5-9386-c793fe2ad091")]
        public string secID
        {
            get { return _secID; }
            set { _secID = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Tab.
        /// </summary>
        [TestVariable("43a54ce5-75bb-4d2e-88b3-ac36f004a6a3")]
        public string Tab
        {
            get { return repo.Tab; }
            set { repo.Tab = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.MenuTab' at Center.", repo.RxMainFrame.MenuTabInfo, new RecordItemIndex(0));
            repo.RxMainFrame.MenuTab.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabDynamicIDs.Chk_ShwDynID' at 7;9.", repo.RxMainFrame.RxTabDynamicIDs.Chk_ShwDynIDInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabDynamicIDs.Chk_ShwDynID.Click("7;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'RxMainFrame.RxTabDynamicIDs.TxtField_CurID' and assigning its value to variable 'firstID'.", repo.RxMainFrame.RxTabDynamicIDs.TxtField_CurIDInfo, new RecordItemIndex(2));
            firstID = repo.RxMainFrame.RxTabDynamicIDs.TxtField_CurID.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabDynamicIDs.Chk_ShwDynID' at Center.", repo.RxMainFrame.RxTabDynamicIDs.Chk_ShwDynIDInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabDynamicIDs.Chk_ShwDynID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'RxMainFrame.RxTabDynamicIDs.TxtField_CurID' and assigning its value to variable 'secID'.", repo.RxMainFrame.RxTabDynamicIDs.TxtField_CurIDInfo, new RecordItemIndex(4));
            secID = repo.RxMainFrame.RxTabDynamicIDs.TxtField_CurID.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabDynamicIDs.Chk_ShwDynID' at Center.", repo.RxMainFrame.RxTabDynamicIDs.Chk_ShwDynIDInfo, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabDynamicIDs.Chk_ShwDynID.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeNotEqual ($firstID!=$secID) on item 'RxMainFrame.RxTabDynamicIDs.TxtField_CurID'.", repo.RxMainFrame.RxTabDynamicIDs.TxtField_CurIDInfo, new RecordItemIndex(6));
            Validate.AttributeNotEqual(repo.RxMainFrame.RxTabDynamicIDs.TxtField_CurIDInfo, firstID, secID);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
