///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemo_Desktop.TestDataBase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Add_TestData recording.
    /// </summary>
    [TestModule("dfac102d-79a9-4aa0-ba82-2d24f56f190a", ModuleType.Recording, 1)]
    public partial class Add_TestData : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDemo_Desktop.RxDemo_DesktopRepository repository.
        /// </summary>
        public static global::RxDemo_Desktop.RxDemo_DesktopRepository repo = global::RxDemo_Desktop.RxDemo_DesktopRepository.Instance;

        static Add_TestData instance = new Add_TestData();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Add_TestData()
        {
            FirstName = "Jagadeesh";
            LastName = "Palavalasa";
            Age = "26";
            Count = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Add_TestData Instance
        {
            get { return instance; }
        }

#region Variables

        string _FirstName;

        /// <summary>
        /// Gets or sets the value of variable FirstName.
        /// </summary>
        [TestVariable("3c4e6ea2-d97f-420a-91ab-e61ddaa3ff4c")]
        public string FirstName
        {
            get { return _FirstName; }
            set { _FirstName = value; }
        }

        string _LastName;

        /// <summary>
        /// Gets or sets the value of variable LastName.
        /// </summary>
        [TestVariable("35d695b5-dc64-47bd-9c5d-52b083b55e8d")]
        public string LastName
        {
            get { return _LastName; }
            set { _LastName = value; }
        }

        string _Age;

        /// <summary>
        /// Gets or sets the value of variable Age.
        /// </summary>
        [TestVariable("b475d073-69df-44a9-97cd-99d2138e12d3")]
        public string Age
        {
            get { return _Age; }
            set { _Age = value; }
        }

        string _Count;

        /// <summary>
        /// Gets or sets the value of variable Count.
        /// </summary>
        [TestVariable("029e98c5-d87d-41e3-9a8b-08d91130d55a")]
        public string Count
        {
            get { return _Count; }
            set { _Count = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Tab.
        /// </summary>
        [TestVariable("43a54ce5-75bb-4d2e-88b3-ac36f004a6a3")]
        public string Tab
        {
            get { return repo.Tab; }
            set { repo.Tab = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable drpdwn.
        /// </summary>
        [TestVariable("a35428b2-b5d9-411d-b81b-46fbe2906657")]
        public string drpdwn
        {
            get { return repo.drpdwn; }
            set { repo.drpdwn = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("047539aa-cac6-4d5f-8dd5-fcf16af36a56")]
        public string Gender
        {
            get { return repo.Gender; }
            set { repo.Gender = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.MenuTab' at Center.", repo.RxMainFrame.MenuTabInfo, new RecordItemIndex(0));
            repo.RxMainFrame.MenuTab.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.TxtField_FirstName' at 32;10.", repo.RxMainFrame.RxTabStandard.TxtField_FirstNameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard.TxtField_FirstName.Click("32;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FirstName' with focus on 'RxMainFrame.RxTabStandard.TxtField_FirstName'.", repo.RxMainFrame.RxTabStandard.TxtField_FirstNameInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabStandard.TxtField_FirstName.PressKeys(FirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.TxtField_LastName' at 22;5.", repo.RxMainFrame.RxTabStandard.TxtField_LastNameInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabStandard.TxtField_LastName.Click("22;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$LastName' with focus on 'RxMainFrame.RxTabStandard.TxtField_LastName'.", repo.RxMainFrame.RxTabStandard.TxtField_LastNameInfo, new RecordItemIndex(4));
            repo.RxMainFrame.RxTabStandard.TxtField_LastName.PressKeys(LastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.Btn_Open' at Center.", repo.RxMainFrame.RxTabStandard.Btn_OpenInfo, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabStandard.Btn_Open.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.drpDwn_Department' at Center.", repo.List1000.drpDwn_DepartmentInfo, new RecordItemIndex(6));
            repo.List1000.drpDwn_Department.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.TxtField_Age' at 14;10.", repo.RxMainFrame.RxTabStandard.TxtField_AgeInfo, new RecordItemIndex(7));
            repo.RxMainFrame.RxTabStandard.TxtField_Age.Click("14;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Clear() on item 'RxMainFrame.RxTabStandard.TxtField_Age'.", repo.RxMainFrame.RxTabStandard.TxtField_AgeInfo, new RecordItemIndex(8));
            repo.RxMainFrame.RxTabStandard.TxtField_Age.Element.InvokeActionWithText("Clear");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Age' with focus on 'RxMainFrame.RxTabStandard.TxtField_Age'.", repo.RxMainFrame.RxTabStandard.TxtField_AgeInfo, new RecordItemIndex(9));
            repo.RxMainFrame.RxTabStandard.TxtField_Age.PressKeys(Age);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.RdBtn_Gender' at Center.", repo.RxMainFrame.RxTabStandard.RdBtn_GenderInfo, new RecordItemIndex(10));
            repo.RxMainFrame.RxTabStandard.RdBtn_Gender.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.Btn_AddEntry' at Center.", repo.RxMainFrame.RxTabStandard.Btn_AddEntryInfo, new RecordItemIndex(11));
            repo.RxMainFrame.RxTabStandard.Btn_AddEntry.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$Count) on item 'RxMainFrame.RxTabStandard.Txt_Entries'.", repo.RxMainFrame.RxTabStandard.Txt_EntriesInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabStandard.Txt_EntriesInfo, "Text", Count);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
