///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemo_Desktop.TestDataBase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Del_TestData recording.
    /// </summary>
    [TestModule("fd14f05d-a6d6-4c4b-a72f-b31b2aef8b62", ModuleType.Recording, 1)]
    public partial class Del_TestData : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDemo_Desktop.RxDemo_DesktopRepository repository.
        /// </summary>
        public static global::RxDemo_Desktop.RxDemo_DesktopRepository repo = global::RxDemo_Desktop.RxDemo_DesktopRepository.Instance;

        static Del_TestData instance = new Del_TestData();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Del_TestData()
        {
            Entries = "";
            Count = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Del_TestData Instance
        {
            get { return instance; }
        }

#region Variables

        string _Entries;

        /// <summary>
        /// Gets or sets the value of variable Entries.
        /// </summary>
        [TestVariable("596b975d-7102-489d-9bd8-700982c7661a")]
        public string Entries
        {
            get { return _Entries; }
            set { _Entries = value; }
        }

        string _Count;

        /// <summary>
        /// Gets or sets the value of variable Count.
        /// </summary>
        [TestVariable("45f1e827-29fb-48d4-8811-25b9cdb9e330")]
        public string Count
        {
            get { return _Count; }
            set { _Count = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable DataBase.
        /// </summary>
        [TestVariable("0a182ed5-9e4b-4524-bca1-ca7aae940f7e")]
        public string DataBase
        {
            get { return repo.DataBase; }
            set { repo.DataBase = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.Txt_DataEnter' at 95;7.", repo.RxMainFrame.RxTabStandard.Txt_DataEnterInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabStandard.Txt_DataEnter.Click("95;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.BtnDeletePerson' at 48;8.", repo.RxMainFrame.RxTabStandard.BtnDeletePersonInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard.BtnDeletePerson.Click("48;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'RxMainFrame.RxTabStandard.Txt_Entries' and assigning its value to variable 'Entries'.", repo.RxMainFrame.RxTabStandard.Txt_EntriesInfo, new RecordItemIndex(2));
            Entries = repo.RxMainFrame.RxTabStandard.Txt_Entries.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='yourtext') on item 'RxMainFrame.RxTabStandard.Txt_Entries'.", repo.RxMainFrame.RxTabStandard.Txt_EntriesInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabStandard.Txt_EntriesInfo, "Text", "yourtext");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$Count) on item 'RxMainFrame.RxTabStandard.Txt_Entries'.", repo.RxMainFrame.RxTabStandard.Txt_EntriesInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabStandard.Txt_EntriesInfo, "Text", Count);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
