///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDemo_Desktop.UploadTesting
{
    public partial class Open_UploadTesting_Tab
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

//        public void Validate_Txt_Finished(RepoItemInfo textInfo)
//        {
//            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Upload Testing') on item 'textInfo'.", textInfo);
//            Validate.AttributeEqual(textInfo, "Text", "Upload Testing");
//        }

        public void Mouse_Click_Btn_Start(RepoItemInfo buttonInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo' at Center.", buttonInfo);
            buttonInfo.FindAdapter<Button>().Click();
        }

        public void validateText(RepoItemInfo buttonInfo, RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'buttonInfo' at Center.", buttonInfo);
            buttonInfo.FindAdapter<Button>().Click();
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Upload Testing') on item 'textInfo'.", textInfo);
            Validate.AttributeEqual(textInfo, "Text", "Upload finished");
        }
        
        public void Mouse_Click_Btn_Reset(RepoItemInfo buttonInfo){
        	buttonInfo.FindAdapter<Button>().Click();
        }

    }
}
