///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxDemo_Desktop.ImageBased
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ImageBased recording.
    /// </summary>
    [TestModule("48b2023e-6039-451c-a2a1-aede9de456a2", ModuleType.Recording, 1)]
    public partial class ImageBased : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxDemo_Desktop.RxDemo_DesktopRepository repository.
        /// </summary>
        public static global::RxDemo_Desktop.RxDemo_DesktopRepository repo = global::RxDemo_Desktop.RxDemo_DesktopRepository.Instance;

        static ImageBased instance = new ImageBased();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ImageBased()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ImageBased Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Tab.
        /// </summary>
        [TestVariable("43a54ce5-75bb-4d2e-88b3-ac36f004a6a3")]
        public string Tab
        {
            get { return repo.Tab; }
            set { repo.Tab = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.MenuTab' at Center.", repo.RxMainFrame.MenuTabInfo, new RecordItemIndex(0));
            repo.RxMainFrame.MenuTab.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabImageBased.Calendar' at 10;6.", repo.RxMainFrame.RxTabImageBased.CalendarInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabImageBased.Calendar.Click(new Location(Calendar_Img_Date20, "10;6", Calendar_Img_Date20_Options));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabImageBased.Calendar' at 9;7.", repo.RxMainFrame.RxTabImageBased.CalendarInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabImageBased.Calendar.Click(new Location(Calendar_Img_Date21, "9;7", Calendar_Img_Date21_Options));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabImageBased.Calendar' at 14;7.", repo.RxMainFrame.RxTabImageBased.CalendarInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabImageBased.Calendar.Click(new Location(Calendar_Img_Date22, "14;7", Calendar_Img_Date22_Options));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabImageBased.Calendar' at 4;4.", repo.RxMainFrame.RxTabImageBased.CalendarInfo, new RecordItemIndex(4));
            repo.RxMainFrame.RxTabImageBased.Calendar.Click(new Location(Calendar_Img_RightArrow, "4;4", Calendar_Img_RightArrow_Options));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabImageBased.Calendar' at 10;6.", repo.RxMainFrame.RxTabImageBased.CalendarInfo, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabImageBased.Calendar.Click(new Location(Calendar_Img_Date20_2, "10;6", Calendar_Img_Date20_2_Options));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabImageBased.Calendar' at 9;7.", repo.RxMainFrame.RxTabImageBased.CalendarInfo, new RecordItemIndex(6));
            repo.RxMainFrame.RxTabImageBased.Calendar.Click(new Location(Calendar_Img_Date21_2, "9;7", Calendar_Img_Date21_2_Options));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabImageBased.Calendar' at 14;7.", repo.RxMainFrame.RxTabImageBased.CalendarInfo, new RecordItemIndex(7));
            repo.RxMainFrame.RxTabImageBased.Calendar.Click(new Location(Calendar_Img_Date22_2, "14;7", Calendar_Img_Date22_2_Options));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabImageBased.ChkBox_ShowImage' at 10;8.", repo.RxMainFrame.RxTabImageBased.ChkBox_ShowImageInfo, new RecordItemIndex(8));
            repo.RxMainFrame.RxTabImageBased.ChkBox_ShowImage.Click("10;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Img_Cat' with region {X=0,Y=0,Width=402,Height=263}) on item 'RxMainFrame.RxTabImageBased.TheCat'.", repo.RxMainFrame.RxTabImageBased.TheCatInfo, new RecordItemIndex(9));
            Validate.ContainsImage(repo.RxMainFrame.RxTabImageBased.TheCatInfo, TheCat_Img_Cat, TheCat_Img_Cat_Options);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Calendar_Img_Date20
        { get { return repo.RxMainFrame.RxTabImageBased.CalendarInfo.GetImg_Date20(new Rectangle(126, 97, 14, 11)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Calendar_Img_Date20_Options
        { get { return Imaging.FindOptions.Default; } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Calendar_Img_Date21
        { get { return repo.RxMainFrame.RxTabImageBased.CalendarInfo.GetImg_Date21(new Rectangle(157, 97, 13, 11)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Calendar_Img_Date21_Options
        { get { return Imaging.FindOptions.Default; } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Calendar_Img_Date22
        { get { return repo.RxMainFrame.RxTabImageBased.CalendarInfo.GetImg_Date22(new Rectangle(188, 97, 18, 11)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Calendar_Img_Date22_Options
        { get { return Imaging.FindOptions.Default; } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Calendar_Img_RightArrow
        { get { return repo.RxMainFrame.RxTabImageBased.CalendarInfo.GetImg_RightArrow(new Rectangle(231, 13, 9, 10)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Calendar_Img_RightArrow_Options
        { get { return Imaging.FindOptions.Default; } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Calendar_Img_Date20_2
        { get { return repo.RxMainFrame.RxTabImageBased.CalendarInfo.GetImg_Date20(new Rectangle(126, 97, 14, 11)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Calendar_Img_Date20_2_Options
        { get { return Imaging.FindOptions.Default; } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Calendar_Img_Date21_2
        { get { return repo.RxMainFrame.RxTabImageBased.CalendarInfo.GetImg_Date21(new Rectangle(157, 97, 13, 11)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Calendar_Img_Date21_2_Options
        { get { return Imaging.FindOptions.Default; } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Calendar_Img_Date22_2
        { get { return repo.RxMainFrame.RxTabImageBased.CalendarInfo.GetImg_Date22(new Rectangle(188, 97, 18, 11)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Calendar_Img_Date22_2_Options
        { get { return Imaging.FindOptions.Default; } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage TheCat_Img_Cat
        { get { return repo.RxMainFrame.RxTabImageBased.TheCatInfo.GetImg_Cat(new Rectangle(0, 0, 402, 263)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions TheCat_Img_Cat_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
